spring:
  output.ansi.enabled: always

  h2:
    console:
      enabled: true
      path: /h2-console

  session:
    store-type: jdbc
    jdbc.initialize-schema: always

  datasource:
#    url: jdbc:h2:tcp://localhost/~/h2db/tmall
    url: jdbc:h2:mem:tipsyboyMall
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        default_batch_fetch_size: 30
        format_sql: true
        highlight_sql: true
    defer-datasource-initialization: true

#logging.level:
#  org.hibernate:
#    type:
#      descriptor:
#        sql: trace

logging.level:
  org.hibernate.SQL: debug

